# These are supported funding model platforms

github: 
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
thanks_dev: 
custom: ["https://www.buymeacoffee.com/narthanan"]
